#! /bin/sh

if [[ $1 = '-32' ]] ; then
	shift
	arch -i386 /usr/bin/auvaltool "$@"
elif [[ $1 = '-ppc' ]] ; then
	shift
	arch -ppc /usr/bin/auvaltool "$@"
else
	arch -x86_64 /usr/bin/auvaltool "$@"
fi
