#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'internetarchive==0.7.5','console_scripts','ia'
__requires__ = 'internetarchive==0.7.5'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('internetarchive==0.7.5', 'console_scripts', 'ia')()
    )
